### ISSUE TITLE
Support for Node 4 (LTS)

### ISSUE THREAD

**Issue by nknapp** [AndreasMadsen/async-hook#5]
I just noticed that the `trace`-package is broken on Node 4.4.3. The reason is probably that `async-hook` now only supports Node 5. 

Could you support Node 4 again? The `trace`packaged worked really well all the time. Better than other long-stack-trace packages. But I also like to use the LTS node version.

**Comment by AndreasMadsen** [comment]
Bump node.js for updating async wrap in Node 4 here: https://github.com/nodejs/LTS/issues/86

or use replace async-hook with version `1.2.0`, since that works with Node 4.

For more details see: https://github.com/AndreasMadsen/trace/issues/24

**Comment by nknapp** [comment]
Ah, I see. Thank you.

**Comment by AndreasMadsen** [comment]
Node.js v4.5.0 is now available. This has the latest AsyncWrap API and thus `trace` should work out of the box.
