### ISSUE TITLE
If one of hook throws, where should it go?

### ISSUE THREAD

**Issue by RobinQu** [AndreasMadsen/async-hook#8]
In the [spec](https://github.com/nodejs/diagnostics/blob/master/tracing/AsyncWrap/README.md#the-hooks) there is a didThrow parameter in `post` hook to indicate the process continues after exception in one of the hooks.

How should I accomplish the behavior above using `async-hook`?

'uncaughtException' event would allow me to handle the exception but it seems impossible to get `uid` of the handle it originates.

**Comment by AndreasMadsen** [comment]
I'm sorry, I don't think I understand the issue. Yes I can see that `didThrow` is missing from the `async-hook` API, I will try and fix that.

**Comment by AndreasMadsen** [comment]
I've added `didThrow` support in https://github.com/AndreasMadsen/async-hook/commit/6d74837c901b2da3ebf70fbc391d642d3af0cede, does that solve the issue?

**Comment by AndreasMadsen** [comment]
I assume it solved the problem. Note that `didThrow` will soon be removed from AsyncWrap. If you are unhappy with that decision and has a good use case, you should tell them here: https://github.com/nodejs/node-eps/pull/18

**Comment by RobinQu** [comment]
Changes are huge......
I am trying to implement Zone in TC39 with async_wrap.
https://github.com/RobinQu/async-zone

**Comment by AndreasMadsen** [comment]
Nice, you ask questions about AsyncWrap here: https://github.com/nodejs/diagnostics
